// Copyright Diego Merayo Merayo. All Rights Reserved

#pragma once

#include "CoreMinimal.h"

#include "Serialization/AssetStructNativeData.h"

struct FAssetPackageDocument;
struct FAssetPackageExportEntry;
struct FAssetPackageTraceCollection;

/** A pin of another node that a pin refers to (a link, a sub pin, the parent): the node that owns it and its id. */
struct FAssetGraphPinReference
{
	/** The owning node as an export or import path. */
	FString Node;
	FGuid Pin;

	bool operator==(const FAssetGraphPinReference& Other) const { return Pin == Other.Pin && Node == Other.Node; }
};

/** One pin of a graph node, as UEdGraphPin::Serialize writes it. */
struct FAssetGraphPin
{
	FGuid PinId;
	FString Name;
	FString FriendlyName;
	FString ToolTip;
	bool bOutput = false;

	/** The type in words: "int", "object (/Script/Engine.Actor)", "array of struct (...)". */
	FString Type;

	FString DefaultValue;
	FString AutogeneratedDefaultValue;
	FString DefaultObject;
	FString DefaultText;

	TArray<FAssetGraphPinReference> LinkedTo;
	TArray<FAssetGraphPinReference> SubPins;
	TArray<FAssetGraphPinReference> Parent;
	TArray<FAssetGraphPinReference> PassThrough;

	FGuid PersistentGuid;
	uint32 Flags = 0;
	int32 SourceIndex = 0;

	/** The names of the flags that are set ("Hidden, AdvancedView"). */
	FString DescribeFlags() const;
};

/**
 * What a graph node (a UEdGraphNode: every node of a Blueprint graph) writes after its tagged properties: its pins, with their types,
 * default values and links. This is the part of a Blueprint graph that changes when a node is connected, disconnected or edited.
 */
struct FAssetGraphNodePins
{
	/** The whole range was read and nothing was left over. When false, Error says where it stopped. */
	bool bComplete = false;
	FString Error;

	/** The bytes the data covers in the document. */
	int64 Offset = 0;
	int64 Size = 0;

	FString ObjectGuid;
	TArray<FAssetGraphPin> Pins;

	/** The pins a node that declares them (an event, a function entry or result) lists as the ones the user defined: name, type, direction and default value. */
	TArray<FAssetGraphPin> UserPins;

	/** A short account: how many pins and how many links. */
	FString Summarize() const;
};

/**
 * Resolves the id of a pin to what people call it ("K2Node_CallFunction_3.Target"), by reading the pins of every graph node of a
 * document the first time it is asked. A link stores only the owner and the id of the pin it goes to.
 */
class FAssetGraphPinNames
{
public:
	FAssetGraphPinNames(const FAssetPackageDocument& InDocument, const FAssetPackageTraceCollection* InTraces) : Document(InDocument), Traces(InTraces) {}

	/** "Node.Pin", or an empty string when no node of the document has that pin. */
	FString Find(const FGuid& PinId) const;

private:
	const FAssetPackageDocument& Document;
	const FAssetPackageTraceCollection* Traces;
	mutable bool bBuilt = false;
	mutable TMap<FGuid, FString> Names;
};

namespace AssetGraphNodePins
{
	/**
	 * Decodes the pins of a graph node export. Returns false, without touching Out, for any export that is not a graph node (its
	 * class is followed through the Blueprint classes of the package to the native class it derives from).
	 *
	 * @param NativeOffset Where the native data starts in the document (right after the tagged properties).
	 * @param NativeSize How many bytes it has.
	 */
	bool Decode(const FAssetPackageDocument& Document, const FAssetPackageExportEntry& Export, int64 NativeOffset, int64 NativeSize, FAssetGraphNodePins& Out);

	/**
	 * What differs between the pins of two versions of a node: pins added or removed, and for a pin that is in both (matched by its
	 * id, which stays when a pin is renamed) its type, direction, default values, links and flags, each pin as one change. Empty when
	 * the pins are the same.
	 */
	TArray<FAssetNativeDataChange> Compare(const FAssetGraphNodePins& Old, const FAssetGraphPinNames& OldNames, const FAssetGraphNodePins& New, const FAssetGraphPinNames& NewNames);

	/**
	 * Reads a pin type (FEdGraphPinType::Serialize: what a pin or a Blueprint variable holds) that starts at Offset, within the bytes
	 * before EndOffset. Returns false when it does not read; otherwise OutType describes it ("int", "array of object (/Script/Engine.Actor)",
	 * "map of name to int") and OutEnd is where it ended.
	 */
	bool ReadPinType(const FAssetPackageDocument& Document, int64 Offset, int64 EndOffset, FString& OutType, int64& OutEnd);

	/** One line about a pin: its name, direction, type, default value and what it is linked to. */
	FString Describe(const FAssetGraphPin& Pin, const FAssetGraphPinNames& Names);
} // namespace AssetGraphNodePins
