// Copyright Diego Merayo Merayo. All Rights Reserved

#include "Serialization/AssetMorphTargetData.h"

#include "Animation/MorphTarget.h"
#include "Misc/SecureHash.h"
#include "UObject/EditorObjectVersion.h"
#include "UObject/FortniteMainBranchObjectVersion.h"
#include "UObject/UE5SpecialProjectStreamObjectVersion.h"

#include "Model/AssetPackageDocument.h"
#include "Serialization/AssetNativeReader.h"
#include "Serialization/AssetSchemaReflection.h"

namespace
{
	/** FMorphTargetDelta: the change of position and of the normal (three floats each), and the index of the vertex they apply to. */
	constexpr int64 DeltaSize = 12 + 12 + 4;

	/** The most LODs a morph target can have in practice; a count beyond it is not a count. */
	constexpr int32 MaximumLods = 64;

	/** Reads a count that must fit what is left of the data, as many elements of ElementSize bytes. */
	int32 ReadFittingCount(FNativeReader& Reader, const int64 ElementSize, const TCHAR* What)
	{
		const int32 Count = Reader.Read<int32>();
		if (Reader.Ok() && (Count < 0 || Count > Reader.Remaining() / FMath::Max<int64>(ElementSize, 1)))
		{
			Reader.Fail(FString::Printf(TEXT("The number of %s does not fit the data"), What));
			return 0;
		}
		return Reader.Ok() ? Count : 0;
	}

	/** FMorphTargetLODModel (MorphTarget.cpp), in the layout since the sections and the engine-generated flag were saved. */
	void ReadLod(FNativeReader& Reader, const FAssetPackageDocument& Document, FAssetMorphTargetLod& Out)
	{
		if (Reader.CustomVer(FEditorObjectVersion::GUID) < FEditorObjectVersion::AddedMorphTargetSectionIndices
			|| Reader.CustomVer(FFortniteMainBranchObjectVersion::GUID) < FFortniteMainBranchObjectVersion::SaveGeneratedMorphTargetByEngine)
		{
			Reader.Fail(TEXT("The LODs of the morph target are stored in an older layout"));
			return;
		}

		// A cook that stores the deltas elsewhere keeps only how many there are.
		bool bStripped = false;
		if (Reader.CustomVer(FUE5SpecialProjectStreamObjectVersion::GUID) >= FUE5SpecialProjectStreamObjectVersion::StripMorphTargetSourceDataForCookedBuilds)
		{
			bStripped = Reader.ReadBool();
		}

		Out.bDeltasStripped = bStripped;
		if (bStripped)
		{
			Out.DeltaCount = Reader.Read<int32>();
		}
		else
		{
			Out.DeltaCount = ReadFittingCount(Reader, DeltaSize, TEXT("vertex deltas"));
			const int64 Bytes = static_cast<int64>(Out.DeltaCount) * DeltaSize;
			const int64 Start = Reader.Tell();
			Reader.Skip(Bytes);
			if (Reader.Ok() && Bytes > 0 && Document.IsValidRange(Start, Bytes))
			{
				Out.DeltaHash = FSHA1::HashBuffer(Document.FileData.GetData() + Start, static_cast<uint64>(Bytes)).ToString().Left(16);
			}
		}

		Out.NumBaseMeshVerts = Reader.Read<int32>();
		Out.SectionCount = ReadFittingCount(Reader, 4, TEXT("sections"));
		Reader.Skip(static_cast<int64>(Out.SectionCount) * 4);
		Out.bGeneratedByEngine = Reader.ReadBool();

		if (Reader.CustomVer(FFortniteMainBranchObjectVersion::GUID) >= FFortniteMainBranchObjectVersion::MorphTargetCustomImport)
		{
			Out.SourceFilename = Reader.ReadString();
		}
	}
} // namespace

FString FAssetMorphTargetLod::Describe() const
{
	FString Text = bDeltasStripped ? FString::Printf(TEXT("%d vertices moved (deltas not kept)"), DeltaCount)
								   : FString::Printf(TEXT("%d vertices moved, deltas %s"), DeltaCount, DeltaHash.IsEmpty() ? TEXT("none") : *DeltaHash);
	Text += FString::Printf(TEXT(", %d base vertices, %d sections"), NumBaseMeshVerts, SectionCount);
	if (bGeneratedByEngine)
	{
		Text += TEXT(", generated by the engine");
	}
	if (!SourceFilename.IsEmpty())
	{
		Text += FString::Printf(TEXT(", from %s"), *SourceFilename);
	}
	return Text;
}

FString FAssetMorphTargetData::Summarize() const
{
	TArray<FString> Parts;
	for (int32 Index = 0; Index < Lods.Num(); ++Index)
	{
		Parts.Add(FString::Printf(TEXT("LOD %d: %d deltas"), Index, Lods[Index].DeltaCount));
	}
	return FString::Printf(TEXT("Morph target: %d LODs%s"), Lods.Num(), Parts.IsEmpty() ? TEXT("") : *(TEXT(" (") + FString::Join(Parts, TEXT(", ")) + TEXT(")")));
}

bool AssetMorphTargetData::Decode(const FAssetPackageDocument& Document, const FAssetPackageExportEntry& Export, const int64 NativeOffset, const int64 NativeSize, FAssetMorphTargetData& Out)
{
	const UClass* NativeClass = AssetSchemaReflection::FindNativeClass(Document, Export.Index);
	if (NativeClass == nullptr || !NativeClass->IsChildOf(UMorphTarget::StaticClass()) || NativeSize <= 0 || !Document.IsValidRange(NativeOffset, NativeSize))
	{
		return false;
	}

	Out = FAssetMorphTargetData();
	Out.Offset = NativeOffset;
	Out.Size = NativeSize;

	FNativeReader Reader(Document, NativeOffset, NativeSize);

	// UObject::Serialize ends with the object's GUID, when it has one.
	if (Reader.ReadBool())
	{
		Out.ObjectGuid = Reader.ReadGuid().ToString(EGuidFormats::DigitsWithHyphens);
	}

	// UMorphTarget::Serialize: strip flags, then nothing more when the render data is stripped (a dedicated server).
	const uint8 GlobalStripFlags = Reader.Read<uint8>();
	Reader.Read<uint8>();
	if (Reader.Ok() && (GlobalStripFlags & 2) == 0)
	{
		// Whether the data is cooked (the deltas are then also stored compressed, for the platforms that need them).
		Out.bCooked = Reader.CustomVer(FFortniteMainBranchObjectVersion::GUID) >= FFortniteMainBranchObjectVersion::MorphTargetCookedCPUDataCompressed && Reader.ReadBool();

		const int32 LodCount = Reader.Read<int32>();
		if (Reader.Ok() && (LodCount < 0 || LodCount > MaximumLods))
		{
			Reader.Fail(TEXT("The number of LODs of the morph target does not make sense"));
		}
		for (int32 Index = 0; Index < LodCount && Reader.Ok(); ++Index)
		{
			ReadLod(Reader, Document, Out.Lods.AddDefaulted_GetRef());
		}

		if (Reader.Ok() && Out.bCooked)
		{
			if (Reader.ReadBool())
			{
				Reader.Fail(TEXT("The compressed deltas of a cooked morph target are not read"));
			}
		}
	}

	if (!Reader.Ok())
	{
		Out.Error = Reader.GetError();
	}
	else if (Reader.Remaining() != 0)
	{
		Out.Error = FString::Printf(TEXT("%lld bytes follow what this reading knows"), Reader.Remaining());
	}
	else
	{
		Out.bComplete = true;
	}

	return true;
}

TArray<FAssetNativeDataChange> AssetMorphTargetData::Compare(const FAssetMorphTargetData& Old, const FAssetMorphTargetData& New)
{
	TArray<FAssetNativeDataChange> Changes;
	if (!Old.bComplete || !New.bComplete)
	{
		return Changes;
	}

	const auto Add = [&Changes](const FString& Key, const FString& Title, const FAssetNativeDataChange::EState State, const FString& OldValue, const FString& NewValue) {
		FAssetNativeDataChange& Change = Changes.AddDefaulted_GetRef();
		Change.Key = Key;
		Change.Title = Title;
		Change.State = State;
		Change.OldValue = OldValue;
		Change.NewValue = NewValue;
	};

	const int32 LodCount = FMath::Max(Old.Lods.Num(), New.Lods.Num());
	for (int32 Index = 0; Index < LodCount; ++Index)
	{
		const FString Key = FString::Printf(TEXT("Lod/%d"), Index);
		const FString Title = FString::Printf(TEXT("LOD %d"), Index);
		if (!Old.Lods.IsValidIndex(Index))
		{
			Add(Key, Title, FAssetNativeDataChange::EState::Added, FString(), New.Lods[Index].Describe());
			continue;
		}
		if (!New.Lods.IsValidIndex(Index))
		{
			Add(Key, Title, FAssetNativeDataChange::EState::Removed, Old.Lods[Index].Describe(), FString());
			continue;
		}

		const FAssetMorphTargetLod& OldLod = Old.Lods[Index];
		const FAssetMorphTargetLod& NewLod = New.Lods[Index];
		const auto Modified = FAssetNativeDataChange::EState::Modified;

		// The deltas: the hash says that a vertex moved even when their number is the same.
		if (OldLod.DeltaCount != NewLod.DeltaCount || (!OldLod.DeltaHash.IsEmpty() && !NewLod.DeltaHash.IsEmpty() && !OldLod.DeltaHash.Equals(NewLod.DeltaHash, ESearchCase::CaseSensitive)))
		{
			Add(Key + TEXT("/Deltas"), Title + TEXT(": vertex deltas"), Modified,
				FString::Printf(TEXT("%d vertices, %s"), OldLod.DeltaCount, OldLod.DeltaHash.IsEmpty() ? TEXT("not kept") : *OldLod.DeltaHash),
				FString::Printf(TEXT("%d vertices, %s"), NewLod.DeltaCount, NewLod.DeltaHash.IsEmpty() ? TEXT("not kept") : *NewLod.DeltaHash));
		}
		if (OldLod.NumBaseMeshVerts != NewLod.NumBaseMeshVerts)
		{
			Add(Key + TEXT("/BaseVertices"), Title + TEXT(": vertices of the base mesh"), Modified, FString::FromInt(OldLod.NumBaseMeshVerts), FString::FromInt(NewLod.NumBaseMeshVerts));
		}
		if (OldLod.SectionCount != NewLod.SectionCount)
		{
			Add(Key + TEXT("/Sections"), Title + TEXT(": sections"), Modified, FString::FromInt(OldLod.SectionCount), FString::FromInt(NewLod.SectionCount));
		}
		if (OldLod.bGeneratedByEngine != NewLod.bGeneratedByEngine)
		{
			Add(Key + TEXT("/Generated"), Title + TEXT(": generated by the engine"), Modified, OldLod.bGeneratedByEngine ? TEXT("yes") : TEXT("no"),
				NewLod.bGeneratedByEngine ? TEXT("yes") : TEXT("no"));
		}
		if (!OldLod.SourceFilename.Equals(NewLod.SourceFilename, ESearchCase::CaseSensitive))
		{
			Add(Key + TEXT("/Source"), Title + TEXT(": source file"), Modified, OldLod.SourceFilename, NewLod.SourceFilename);
		}
	}

	return Changes;
}
